spring:
  profiles:
    active: dev


  #要严格解析XML格式的文档，遇到不闭合标签会报这个错误
  thymeleaf:
        mode: LEGACYHTML5
        # 模板缓存开关
        cache: false
        access_log_enabled: true
        basedir: target/tomcat

  mybatis:
       type-aliases-package: com.neo.entity

  datasource:
          name: talk
          url: jdbc:mysql://127.0.0.1:3306/talk
          username: root
          password: root
          # 使用druid做数据连接池
          type: com.alibaba.druid.pool.DruidDataSource
          driver-class-name: com.mysql.jdbc.Driver
          filters: stat
          maxActive: 20
          initialSize: 1
          maxWait: 60000
          minIdle: 1
          timeBetweenEvictionRunsMillis: 60000
          minEvictableIdleTimeMillis: 300000
          validationQuery: select 'x'
          testWhileIdle: true
          testOnBorrow: false
          testOnReturn: false
          poolPreparedStatements: true
          maxOpenPreparedStatements: 20